language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer config -g process-timeout 9000 && composer update --ignore-platform-reqs
  - phpenv config-rm xdebug.ini

script:
  - composer test